name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  compile:
    name: Create resume pdf
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run build
        uses: addnab/docker-run-action@v3
        with:
          image: thomasweise/docker-texlive-full:latest
          options: -v ${{ github.workspace }}:/data -e MAIL=${{ secrets.MAIL }} -e PHONE=${{ secrets.PHONE }} -e PHONE_LINK=${{ secrets.PHONE_LINK }}
          run: |
            cd data
            MAIL="${MAIL:-keepthat@priva.te}"
            PHONE="${PHONE:-+33 X XX XX XX XX}"
            PHONE_LINK="${PHONE_LINK:-+33XXXXXXXXX}"
            pdflatex -jobname clement-omnes-resume "\def\resumeMail{$MAIL}\def\resumePhone{$PHONE}\def\resumePhoneLink{$PHONE_LINK}\input{resume}"
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "feat(pdf): update resume pdf"
